# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [252]:
# No code solution (reading)
import torch

In [253]:
x = torch.tensor([[1.0,-1],[1,1]], requires_grad=True, device='cpu')

In [254]:
out = x.pow(2).sum()

In [255]:
out

tensor(4., grad_fn=<SumBackward0>)

In [256]:
out.backward()

In [257]:
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [258]:
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

### 2. Create a random tensor with shape `(7, 7)`.


In [259]:
# Import torch

import torch
# Create random tensor
torch.manual_seed(42)
mat_2 = torch.rand(size=(7,7))


In [260]:
import numpy as np

In [261]:
np.random.seed(42)
np.random.rand(3,3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [262]:
# Create another random tensor
mat_3 = torch.rand(size=(1,7))


In [263]:
# Perform matrix multiplication 
res = torch.mm(mat_2, mat_3.T)

In [264]:
res

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])

In [265]:
mat_1 = torch.ones(size=(7,7))
mat_2 = torch.ones(size=(1,7))*3

In [266]:
mat_1

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [267]:
mat_2

tensor([[3., 3., 3., 3., 3., 3., 3.]])

In [268]:
mat_1 * mat_2.T

tensor([[3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [269]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
mat_a = torch.rand(size=(7,7))
mat_b = torch.rand(size=(1,7))

# Matrix multiply tensors
res = torch.mm(mat_a, mat_b.T)
res


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [270]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [271]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
mat_a = torch.rand(size=(2,3), device='cuda')
mat_b = torch.rand(size=(2,3), device='cuda')


True


In [ ]:
sum(list(range(100)))

7626

In [286]:
import statistics

In [272]:
mat_a, mat_b

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [ ]:
# import torch

# # Ensure full reproducibility
# torch.manual_seed(1234)                 # Set seed for CPU
# torch.cuda.manual_seed(1234)             # Set seed for current GPU
# torch.cuda.manual_seed_all(1234)         # Set seed for all GPUs (if using multi-GPU)
# torch.backends.cudnn.deterministic = True  # Force deterministic CUDA behavior
# torch.backends.cudnn.benchmark = False  

# # Create random tensors on GPU
# mat_a = torch.rand(size=(2,3), device='cuda')
# mat_b = torch.rand(size=(2,3), device='cuda')

print(mat_a, mat_b)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [277]:
# Perform matmul on tensor_A and tensor_B
res_7 = torch.matmul(mat_a, mat_b.T)
res_7

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [276]:
# Find max
print('max' , torch.max(res_7).item())
# Find min
print('min', torch.min(res_7).item())


max 0.7667766809463501
min 0.27863210439682007


In [279]:
torch.max(res_7)

tensor(0.7668, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [282]:
# Find arg max
print('index_max ', torch.argmax(res_7).item())

# Find arg min
print('index_min', torch.argmin(res_7).item())


index_max  1
index_min 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [284]:
# Set seed
torch.manual_seed(7)
torch.cuda.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()
print(random_tensor_squeezed.size())

# Print out tensors and their shapes
print("original tensor\n", random_tensor)
print("shape of original tensor: ", random_tensor.size())


print("Squeezed tensor\n", random_tensor_squeezed)
print("shape of squeezed tensor: ", random_tensor_squeezed.size())


torch.Size([10])
original tensor
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
shape of original tensor:  torch.Size([1, 1, 1, 10])
Squeezed tensor
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
shape of squeezed tensor:  torch.Size([10])


In [287]:
import statistics

In [296]:
np.random.randint(5,50,5)

array([32, 48, 48, 24, 34])

In [306]:
a = list(np.random.randint(low=5, high=50, size=(50)).astype(float))

In [307]:
a

[28.0,
 9.0,
 38.0,
 10.0,
 26.0,
 15.0,
 20.0,
 37.0,
 13.0,
 10.0,
 20.0,
 33.0,
 7.0,
 24.0,
 40.0,
 23.0,
 30.0,
 7.0,
 23.0,
 24.0,
 36.0,
 11.0,
 45.0,
 37.0,
 44.0,
 43.0,
 22.0,
 44.0,
 5.0,
 15.0,
 32.0,
 29.0,
 27.0,
 35.0,
 34.0,
 46.0,
 39.0,
 11.0,
 20.0,
 30.0,
 6.0,
 5.0,
 16.0,
 9.0,
 41.0,
 36.0,
 13.0,
 45.0,
 39.0,
 23.0]

In [308]:
statistics.mean(a)

25.5

In [309]:
statistics.mode(a)

20.0

In [310]:
statistics.median(a)

25.0

In [311]:
statistics.stdev(data=a)

12.817796938918441

In [312]:
statistics.quantiles(a)

[13.0, 25.0, 37.0]